pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '8.x'

- script: npm install
  displayName: 'NPM Install'

- script: wget -P out https://cdnjs.cloudflare.com/ajax/libs/webrtc-adapter/7.2.3/adapter.min.js
  displayName: 'Download Minified'

- task: Npm@1
  displayName: 'NPM Publish'
  inputs:
    command: publish
    publishEndpoint: 'npm registry'
